# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-01 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(default='IN', max_length=3)),
                ('zip_code', models.IntegerField()),
                ('discrimination_description', models.CharField(max_length=2000)),
                ('offending_party', models.CharField(max_length=128)),
                ('offender_type', models.CharField(choices=[(1, 'Business'), (2, 'Person')], max_length=32)),
                ('offender_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('offender_address', models.CharField(max_length=128, null=True)),
                ('offender_city', models.CharField(max_length=64, null=True)),
                ('offender_state', models.CharField(default='IN', max_length=2, null=True)),
                ('offender_zip_code', models.IntegerField(null=True)),
                ('descrimination_type', models.CharField(choices=[(1, 'Employment (terminated, hours cut, suspended, denied employment, etc.)'), (2, 'Housing (evicted, denied a house or apartment, subjected to different terms and conditions, etc.)'), (3, 'Public Accommodation (denied access to services, etc.)'), (4, 'Credit (denied a loan, subjected to different terms or conditions, etc.)'), (5, 'Education (special education services, disparate discipline, etc.)')], max_length=128)),
                ('descrimination_date', models.DateField()),
                ('descrimination_basis', models.CharField(choices=[(1, 'Age'), (2, 'Ancestry'), (3, 'Color'), (4, 'Disability'), (5, 'Race'), (6, 'Religion'), (7, 'Sex'), (8, 'Retaliation'), (9, 'Familial Status'), (10, 'National Origin')], max_length=32)),
                ('reference', models.CharField(choices=[(1, 'Attorney/Lawyer'), (2, 'Government Agency'), (3, 'Friend'), (4, 'Advertisement'), (5, 'Brochure/Poster'), (6, 'Internet')], max_length=32)),
                ('signature', models.CharField(max_length=256)),
            ],
        ),
    ]
