# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date_filed',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date_of_act',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='date_of_disposition',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='offender_number_of_employees',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='related_offender_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='complaint',
            name='secondary_address',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='complaint',
            name='secondary_city',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='complaint',
            name='secondary_email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='complaint',
            name='secondary_first_name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='complaint',
            name='secondary_last_name',
            field=models.CharField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='complaint',
            name='secondary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=128),
        ),
        migrations.AddField(
            model_name='complaint',
            name='secondary_state',
            field=models.CharField(default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='complaint',
            name='secondary_zip_code',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status_or_disposition',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='discrimination_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='discrimination_description',
            field=models.CharField(default=None, max_length=2000),
        ),
    ]
