# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-20 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_form', '0002_auto_20180804_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='date_filed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_of_act',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='date_of_disposition',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='discrimination_basis',
            field=models.CharField(choices=[('1', 'Age'), ('2', 'Ancestry'), ('3', 'Color'), ('4', 'Disability'), ('5', 'Race'), ('6', 'Religion'), ('7', 'Sex'), ('8', 'Retaliation'), ('9', 'Familial Status'), ('10', 'National Origin')], max_length=32),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='discrimination_type',
            field=models.CharField(choices=[('1', 'Employment (terminated, hours cut, suspended, denied employment, etc.)'), ('2', 'Housing (evicted, denied a house or apartment, subjected to different terms and conditions, etc.)'), ('3', 'Public Accommodation (denied access to services, etc.)'), ('4', 'Credit (denied a loan, subjected to different terms or conditions, etc.)'), ('5', 'Education (special education services, disparate discipline, etc.)')], max_length=128),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='offender_type',
            field=models.CharField(choices=[('1', 'Business'), ('2', 'Person')], max_length=32),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reference',
            field=models.CharField(choices=[('1', 'Attorney/Lawyer'), ('2', 'Government Agency'), ('3', 'Friend'), ('4', 'Advertisement'), ('5', 'Brochure/Poster'), ('6', 'Internet')], max_length=32),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='related_offender_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='secondary_address',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='secondary_city',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='secondary_email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='secondary_first_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='secondary_last_name',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='secondary_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='secondary_state',
            field=models.CharField(blank=True, default='IN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='secondary_zip_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status_or_disposition',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
